feat: Add default user groups
ubuntu/authd pull request #255
Opened 2024-03-15 14:37 UTC by denisonbarbosa

We used to rely entirely on the groups information provided by the broker, but this is unreasonable since we have some default groups in unix systems that are "required" but only make sense in the OS context.

To prevent errors and reduce frustration from misconfiguration, we now ensure that the user will always be a part of his own group and part of the "users" group as well.

2024-03-18 13:24 UTC, denisonbarbosa commented on internal/brokers/broker.go
> +	uInfo.UserInfo.Groups = append(defaultGroups, uInfo.UserInfo.Groups...)
I think we can look at [adduser.conf](https://manpages.ubuntu.com/manpages/noble/en/man5/adduser.conf.5.html) and grab the defaults from there. I do have some concerns regarding complexity and layers of configuration, though (i.e. we could be expecting too much from the user).

2024-03-18 13:24 UTC, 3v1n0 commented on internal/brokers/broker.go
> +	uInfo.UserInfo.Groups = append(defaultGroups, uInfo.UserInfo.Groups...)
Yeah, it seems more configuration-scenario to me too.

2024-03-19 06:57 UTC, didrocks requested changes
Summary from the meeting:
- only create a main group matching the user's group and add it automatically as the main group of the user.
- do not add to any other groups for now.

This gives the least amount of surprise for the directory administrator.

2024-03-19 16:07 UTC, didrocks approved these changes
One minor variable name comment, but then, should be good to merge!

2024-03-19 16:07 UTC, didrocks commented on internal/brokers/broker.go
> +	defaultGroups := []users.GroupInfo{{Name: uInfo.Name, GID: &uInfo.UID}}
it’s `defaultGroup` for now :)

2024-03-20 12:23 UTC, merged