debian/pam-configs/authd: Be stricter on failures
ubuntu/authd pull request #273
Opened 2024-03-26 15:58 UTC by 3v1n0

- If authd ignored the request, then we should ignore too.
 - If we can't connect to authd, we should ignore to select next method.
 - If we fail hard for other reason, then user should not be authenticated.

Removed the handling of user_unknown case because we never return this from the PAM module for security reasons.

2024-03-28 11:24 UTC, denisonbarbosa requested changes
These changes work when logging in with an authd user: great!
But they block login with a local one (possibly due to the previously discussed issues with `gdm_authd` that does not set the previously selected broker correctly for the user): bad!!

This needs to wait until the mentioned issue is fixed.

2024-07-03 12:49 UTC, 3v1n0 commented
The very same change on failing early was now covered by #406.

However @didrocks we have some cases in which we return `pam.ErrAuthinfoUnavail` in where we maybe we should ignore, thus the mapping here, but since you tested this lately let me know if it still stands.

2024-07-03 13:09 UTC, didrocks commented
that could be a good while, let’s stage this to see when we do trigger this error and see if we need to add it.

2024-12-12 12:10 UTC, denisonbarbosa approved these changes

2024-12-12 19:01 UTC, merged